_wandb:
    value:
        cli_version: 0.20.1
        code_path: code/myosuite/envs/myo/myowheelchair/ParallelTrainingScriptWandB.py
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 34
                - 35
                - 55
            "4": 3.12.2
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
CR:
    value: 0.2
activation:
    value: relu
dense_units:
    value: 512
entropy:
    value: 0.01
env_name:
    value: myoHandWheelHoldFixed-v0
loaded_model:
    value: NA
lr:
    value: 0.0005
max_episode_steps:
    value: 200
name:
    value: 2025_07_31_16_29_500PPO
num_envs:
    value: 1
policy_type:
    value: PPO
seed:
    value: 0
total_timesteps:
    value: 1e+06
