_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/myosuite/envs/myo/myowheelchair/ParallelTrainingScriptWandB.py
        e:
            8sag0hwh6b8396rwn75lv9l8yaqew12a:
                codePath: myosuite\envs\myo\myowheelchair\ParallelTrainingScriptWandB.py
                codePathLocal: myosuite\envs\myo\myowheelchair\ParallelTrainingScriptWandB.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1021821579264"
                        used: "276392357888"
                email: jasmine.jh.wang04@gmail.com
                executable: C:\Users\jasmi\miniconda3\envs\MyoSuite\python.exe
                git:
                    commit: 5dfee51c906a68156e9299df583f4b0c3c0e14f4
                    remote: https://github.com/olibreadstick/myosuite.git
                host: Jas-P14S
                memory:
                    total: "29706903552"
                os: Windows-10-10.0.26100-SP0
                program: c:/Users/jasmi/Documents/GitHub/myosuite/myosuite/envs/myo/myowheelchair/ParallelTrainingScriptWandB.py
                python: CPython 3.8.20
                root: C:\Users\jasmi\Documents\GitHub\myosuite
                startedAt: "2025-07-21T21:07:19.738681Z"
                writerId: 8sag0hwh6b8396rwn75lv9l8yaqew12a
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
                - 35
            "4": 3.8.20
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
CR:
    value: 0.2
activation:
    value: relu
dense_units:
    value: 512
entropy:
    value: 0.01
env_name:
    value: myoHandWheelHoldFixed-v0
loaded_model:
    value: NA
lr:
    value: 0.0005
max_episode_steps:
    value: 200
name:
    value: 2025_07_21_17_07_190PPO
num_envs:
    value: 1
policy_type:
    value: PPO
seed:
    value: 0
total_timesteps:
    value: 500000
