_current_progress_remaining:
    value: 0.950848
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 0.      -0.       0.29733 ...  0.       0.       0.     ]
         [ 0.      -0.       0.29733 ...  0.       0.       0.     ]
         [ 0.      -0.       0.29733 ...  0.       0.       0.     ]
         ...
         [ 0.      -0.       0.29733 ...  0.       0.       0.     ]
         [ 0.      -0.       0.29733 ...  0.       0.       0.     ]
         [ 0.      -0.       0.29733 ...  0.       0.       0.     ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x29957ea20>
_n_updates:
    value: 700
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 2e+06
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.20.1
        code_path: code/myosuite/envs/myo/myowheelchair/ParallelTrainingScriptWandB.py
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
                - 22
                - 34
                - 35
                - 55
            "4": 3.12.2
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-arm64
CR:
    value: 0.2
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (63,), float32)
activation:
    value: relu
algo:
    value: PPO
batch_size:
    value: 256
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x298d879c0>
clip_range_vf:
    value: None
dense_units:
    value: 512
device:
    value: cpu
ent_coef:
    value: 0.001
entropy:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x167ca43e0>
env_name:
    value: myoHandWheelHoldFixed-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
loaded_model:
    value: NA
lr:
    value: 0.0005
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x17c65a700>
max_episode_steps:
    value: 500
max_grad_norm:
    value: 0.5
n_envs:
    value: 12
n_epochs:
    value: 10
n_steps:
    value: 4096
name:
    value: 2025_08_19_11_48_520PPO
normalize_advantage:
    value: "True"
num_envs:
    value: 1
num_timesteps:
    value: 0
observation_space:
    value: Box(-10.0, 10.0, (178,), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=178, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
            )
            (value_net): Sequential(
              (0): Linear(in_features=178, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
            )
          )
          (action_net): Linear(in_features=256, out_features=63, bias=True)
          (value_net): Linear(in_features=256, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''activation_fn'': <class ''torch.nn.modules.activation.ReLU''>, ''net_arch'': {''pi'': [256, 256], ''vf'': [256, 256]}}'
policy_type:
    value: PPO
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x166ff79b0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 0
start_time:
    value: 1755618547992092000
target_kl:
    value: None
tensorboard_log:
    value: runs/2025_08_19_11_48_55
total_timesteps:
    value: 1e+06
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
